# Generated by Django 4.1.2 on 2022-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('anons', models.CharField(max_length=300, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.DeleteModel(
            name='Artiles',
        ),
    ]
